module Layered
  module Ui
    module Generators
      class CopyAssetsGenerator < Rails::Generators::Base
        desc "Copy layered-ui-rails CSS assets into the host application"

        def self.source_root
          Layered::Ui::Engine.root
        end

        def copy_css
          source_path = File.join(self.class.source_root, "app/assets/tailwind/layered/ui/styles.css")
          source_content = File.read(source_path)

          header = <<~CSS
            /*
             * layered-ui-rails v#{Layered::Ui::VERSION}
             *
             * This file was automatically generated by the layered:ui:install generator.
             * Do not modify directly. To update, re-run: bin/rails generate layered:ui:install
             */

          CSS

          create_file "app/assets/tailwind/layered_ui.css", header + source_content
        end
      end
    end
  end
end
